# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  name: 'DownloadIPA'
  inputs:
    secureFileId: 'ipa-file'
    # specify the target path to download the file
    # in this example, the file will be downloaded to $(Pipeline.Workspace)/ipa
    # you can change this to any other path
    destination: '$(Pipeline.Workspace)/ipa'

- task: PublishPipelineArtifact@1
  name: 'PublishIPA'
  inputs:
    # specify the artifact name
    artifactName: 'DVIA'
    # specify the source path of the artifact
    # in this example, the source path is $(Pipeline.Workspace)/ipa/DamnVulnerableiOSApp.ipa
    # you can change this to any other path where your downloaded IPA file is located
    targetPath: '$(Pipeline.Workspace)/ipa/DamnVulnerableiOSApp.ipa'

- script: |
    curl -L -o "$(System.ArtifactsDirectory)/DVIA/DamnVulnerableiOSApp.ipa" "https://github.com/jqtpru103/DVIA/raw/main/DamnVulnerableiOSApp/DamnVulnerableiOSApp.ipa"
  displayName: 'Download File'

#- task: DownloadFile@1
#  inputs:
#    sourceUrl: 'https://github.com/jqtpru103/DVIA/DamnVulnerableiOSApp.ipa'
#    targetPath: '$(System.ArtifactsDirectory)/app.ipa'
#- task: PublishPipelineArtifact@1
#  inputs:
#    artifactName: 'App'
#    path: '$(System.ArtifactsDirectory)/app.ipa'

#- task: PublishPipelineArtifact@1
#  inputs:
#    artifactName: 'DVIA'
#    path: '$(System.ArtifactsDirectory)/DVIA'

- script: echo This is a test
  displayName: 'Run a one-line script'


