# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  artifactName: 'DVIA'

# Define pipeline steps
steps:
  # Download the DamnVulnerableiOSApp.ipa file from the forked repository
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: '$(artifactName)'
      path: '$(System.ArtifactsDirectory)/$(artifactName)'
      runVersion: 'latest'
      downloadType: 'single'
      itemPattern: 'DamnVulnerableiOSApp.ipa'

  # Publish the DamnVulnerableiOSApp.ipa file as a pipeline artifact
  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: '$(artifactName)'
      targetPath: '$(System.ArtifactsDirectory)/$(artifactName)/DamnVulnerableiOSApp.ipa'
      publishLocation: 'pipeline'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
