# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    artifact: 'DVIA'
    path: '$(System.ArtifactsDirectory)/DVIA'
  condition: succeededOrFailed()

- script: |
    curl -L -o "$(System.ArtifactsDirectory)/DVIA/DamnVulnerableiOSApp.ipa" "https://github.com/jqtpru103/DVIA/raw/main/DamnVulnerableiOSApp/DamnVulnerableiOSApp.ipa"
  displayName: 'Download File'

#- task: DownloadFile@1
#  inputs:
#    sourceUrl: 'https://github.com/jqtpru103/DVIA/DamnVulnerableiOSApp.ipa'
#    targetPath: '$(System.ArtifactsDirectory)/app.ipa'
#- task: PublishPipelineArtifact@1
#  inputs:
#    artifactName: 'App'
#    path: '$(System.ArtifactsDirectory)/app.ipa'

#- task: PublishPipelineArtifact@1
#  inputs:
#    artifactName: 'DVIA'
#    path: '$(System.ArtifactsDirectory)/DVIA'

- script: echo This is a test
  displayName: 'Run a one-line script'


