# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    artifact: 'DVIA'
    path: '$(System.ArtifactsDirectory)/DVIA'
    downloadType: 'single'

- script: |
    # Navigate to the directory containing the .ipa file
    cd $(System.ArtifactsDirectory)/DVIA
    # Copy the .ipa file to the artifacts staging directory
    cp DamnVulnerableiOSApp.ipa $(Build.ArtifactStagingDirectory)
  displayName: 'Copy .ipa file to artifacts staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'DVIA.ipa'
    pathToPublish: '$(Build.ArtifactStagingDirectory)'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
